version: 2.1

defaults: &defaults
  docker:
    - image: cimg/python:3.8

orbs:
  python: circleci/python@1.2

workflows:
  branch-validation:
    jobs:
      - build
      - tests:
          requires:
            - build


jobs:
  build:  
    <<: *defaults
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

  tests:
    <<: *defaults
    steps:
      - checkout
#      - python/restore-packages:
#          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

