version: 2.1

defaults: &defaults
  docker:
    - image: cimg/python:3.8

restore_deps: &restore_deps
  restore_cache:
    key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

orbs:
  python: circleci/python@1.2

workflows:
  branch-validation:
    jobs:
      - build
      - tests:
          requires:
            - build


jobs:
  build:  
    <<: *defaults
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths: 
            - "venv"

  tests:
    <<: *defaults
    steps:
      - checkout
      - *restore_deps
      - run:
          name: Run tests
          command: pytest

